import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google" 
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/components/Providers";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="dark">
      <body className={cn("min-h-screen dark:bg-gray-950 bg-white text-white font-sans antialiased", fontSans.variable)}>
        <Providers>
          <main>{children}</main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
